### PR TITLE
[DashboardLayout] Add width containment on flex container

### LINKED ISSUE #4407: [example][pageContainer] Unable to scroll a Datagrid
### Steps to reproduce

Steps:
1. Open the custom-themed example from: https://mui.com/toolpad/core/introduction/examples/ in codesandbox. (Stackblitz doesn't work)
2. In a smaller window, you'll notice that the datagrid doesn't scroll (as shown in the video)
3. It scrolls in https://mui.com/material-ui/getting-started/templates/dashboard/

https://github.com/user-attachments/assets/56cfd0cf-f188-4a1e-a70b-6bef163f85e5

**Search keywords**: datagrid

### PR DESCRIPTION
**Pull request by bharatkashyap**
- Fixes #4407 
- Closes https://github.com/mui/toolpad/issues/4387
- Adds a `{ position: relative, maxWidth: 100% }` to the flex container inside `DashboardLayout` to add max-width containment and enable the children to scroll

- StackBlitz showing corrected behaviour https://stackblitz.com/edit/vitejs-vite-vk9u7p

### CODE REVIEW

**Review by ydainna — APPROVED** [review]

**Comment by Janpot** [comment]
why max width? shouldn't the container just be the width of the available space, regardless of the content?

**Comment by bharatkashyap** [comment]
> why max width? shouldn't the container just be the width of the available space, regardless of the content?

You're right, the fix works because of the `min-width` and not the `max-width`:

https://github.com/user-attachments/assets/70ae5621-7a95-436e-b3e6-99c36488b8d9

**Review by apedroferreira — APPROVED** [review]
This seems to do it. Thanks a lot, Bharat!

**Comment by alexwork1611** [comment]
Glad you guys figured it out.

**Pull request merged**
