### PR TITLE
[DashboardLayout] Support collapsed mini-drawer by default

### PR DESCRIPTION
**Pull request by apedroferreira**
Add `defaultSidebarCollapsed` prop to `DashboardLayout` to start with mini-drawer on desktop-sized screens.
Includes test and docs demo.

Closes https://github.com/mui/toolpad/issues/4172

https://deploy-preview-4234--mui-toolpad-docs.netlify.app/toolpad/core/react-dashboard-layout/#start-with-mini-drawer-on-desktop

### CODE REVIEW

**Comment by prakhargupta1** [comment]
@apedroferreira If this is close to completion can it be a part of v0.8.0? Another user [requested](https://discord.com/channels/1131323012554174485/1288949507375239280/1295844294019645450) this.

**Comment by apedroferreira** [comment]
> @apedroferreira If this is close to completion can it be a part of v0.8.0? Another user [requested](https://discord.com/channels/1131323012554174485/1288949507375239280/1295844294019645450) this. CC: @Janpot

Just needs a review and to be rebased, so it should be possible to include it?

**Comment by apedroferreira** [comment]
Also not sure if `initialSidebarCollapsed` would be a better name for the prop or not.

**Comment by Janpot** [comment]
> Also not sure if initialSidebarCollapsed would be a better name for the prop or not.

What do core components do?

**Review by Janpot — APPROVED** [review]

**Comment by apedroferreira** [comment]
> > Also not sure if initialSidebarCollapsed would be a better name for the prop or not.
> 
> What do core components do?

`default` seems more common, let's stick with it.
- defaultValue in components like <TextField> or <Select>.
- defaultChecked in <Checkbox> and <Switch> components.

There are some exceptions like `initialState` in the DataGrid but `default` seems good.

**Pull request merged**
