### PR TITLE
add prop sidebarCollapsed and onToggleSidebar

### PR DESCRIPTION
**Pull request by vikasgurjar**
Closes [#4406](https://github.com/mui/toolpad/issues/4406)

- [x] I've read and followed the [contributing guide](https://github.com/mui/toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [x] I've updated the relevant documentation for any new or updated feature.
- [x] I've linked relevant GitHub issue with "Closes #<issue id>".
- [ ] I've added a visual demonstration in the form of a screenshot or video.

### CODE REVIEW

**Comment by Janpot** [comment]
I'm wondering if we should maintain the convention of naming a controlled prop "xyz" + "onXyzChange".

**Comment by vikasgurjar** [comment]
> _edit: actually, it looks like the data grid has the convention of "xyzOpen", "onXyzOpen" and "onXyzClose". Perhaps that's the closest in spirit?_

Are you suggesting to have two different callbacks for open and close events? `onSidebarOpen` and `onSidebarClosed`?

Also can you help me with pointing out why some of the checks are failing?

**Comment by bharatkashyap** [comment]
> Also can you help me with pointing out why some of the checks are failing?

- When changing any of the prop types, make sure to run `pnpm docs:typescript:formatted` to autogenerate prop type changes
- The `ml` change from 1 to 0.5 is causing a Argos to complain about the visual diff, not really sure if that margin reduction is required though, is it?

**Comment by vikasgurjar** [comment]
> * When changing any of the prop types, make sure to run `pnpm docs:typescript:formatted` to autogenerate prop type changes

I ran that command before raising the PR. What I have noticed is [this lines](https://github.com/mui/toolpad/blob/29cdab0d1d15158932ed5b700836c6b99b8df8a9/docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSidebarCollapsedProp.js#L66) props are wrongly generated. Correct proptype should be `Proptype.func.required` I think.

> * The `ml` change from 1 to 0.5 is causing a Argos to complain about the visual diff, not really sure if that margin reduction is required though, is it?
I did not make any such changes

**Comment by bharatkashyap** [comment]
> I did not make any such changes
I'm talking about https://github.com/mui/toolpad/pull/4514/files#diff-a60abe0d3acc649d38279fd6f3f7a3b1537b0515b42f476b3a52a30d7b67ddb0L131, https://github.com/mui/toolpad/pull/4514/files#diff-a60abe0d3acc649d38279fd6f3f7a3b1537b0515b42f476b3a52a30d7b67ddb0L377 and https://github.com/mui/toolpad/pull/4514/files#diff-a60abe0d3acc649d38279fd6f3f7a3b1537b0515b42f476b3a52a30d7b67ddb0L386

**Comment by vikasgurjar** [comment]
I will just raise another PR, made some mistakes while rebasing last time

**Pull request closed without merging**
